CREATE TABLE USER (
	USER_ID INT NOT NULL,
	EMAIL VARCHAR(100) NULL,
	NAME VARCHAR(50) NULL,
	PASSWORD VARCHAR(20) NULL,
	PRIMARY KEY (USER_ID)
);
	
GRANT ALL PRIVILEGES ON niceplace.user TO 'root'@'%' WITH GRANT OPTION;

INSERT INTO USER (USER_ID, NAME, EMAIL, PASSWORD ) VALUES (100, 'Brunno de Almeida Santos', 'balmeida.santos@hotmail.com  a ','1234');
INSERT INTO USER (USER_ID, NAME, EMAIL, PASSWORD ) VALUES (101, 'Joazinho', 'joaozinho@hotmail.com','1234');
INSERT INTO USER (USER_ID, NAME, EMAIL, PASSWORD ) VALUES (102, 'Maria', 'maria@hotmail.com','1234');


CREATE TABLE PLACE(
	PLACE_ID INT NOT NULL,
	NAME VARCHAR(50) NULL,
	PHONE VARCHAR(20) NULL,
	TYPE VARCHAR(30),
	PRIMARY KEY (PLACE_ID)
);

GRANT ALL PRIVILEGES ON niceplace.PLACE TO 'root'@'%' WITH GRANT OPTION;

INSERT INTO PLACE (PLACE_ID, NAME, PHONE) VALUES (200, 'LIVRARIA', '48-3333-3333','LIBRARY');
INSERT INTO PLACE (PLACE_ID, NAME, PHONE) VALUES (201, 'CAFE', '48-4444-4444','COFFEE');
INSERT INTO PLACE (PLACE_ID, NAME, PHONE) VALUES (202, 'MCDONALDS', '48-5555-5555','RESTAURANT');


CREATE TABLE USER_PLACE (
  	USER_ID INT(10) UNSIGNED NOT NULL,
  	PLACE_ID INT(10) UNSIGNED NOT NULL,
  	SCORE INT NOT NULL,
  	RATED_DATE DATE NOT NULL,
 	PRIMARY KEY (USER_ID, PLACE_ID),
  	CONSTRAINT FK_PLACE_ID FOREIGN KEY (PLACE_ID) REFERENCES PLACE (PLACE_ID),
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID)
);

GRANT ALL PRIVILEGES ON niceplace.USER_PLACE TO 'root'@'%' WITH GRANT OPTION;

INSERT INTO USER_PLACE (USER_ID, PLACE_ID, SCORE, RATED_DATE) VALUES (100,200,5, NOW());
INSERT INTO USER_PLACE (USER_ID, PLACE_ID, SCORE, RATED_DATE) VALUES (101,201,4, NOW());
INSERT INTO USER_PLACE (USER_ID, PLACE_ID, SCORE, RATED_DATE) VALUES (102,202,3, NOW());
